#!/bin/bash

version=$1

if [ "$version" = "" ]; then
    echo "Usage: publish <version>"
    exit
fi

if [ "$version" = "snapshot" ]; then
    version=`date +%Y%m%d`
fi

cd /tmp

cvs -d /usr/local/cvsroot co reticule

mv reticule reticule-$version
cd reticule-$version/phaeton
autoconf
cd ../..

tar czvf reticule-$version.tar.gz reticule-$version
rm -r reticule-$version

mv reticule-$version.tar.gz ~www/reticule/html
cd ~www/reticule/html
rm -f reticule-snapshot.tar.gz 
ln -s reticule-$version.tar.gz reticule-snapshot.tar.gz 

